=head1 NAME

App::Shiroh - CLI posting tool for twitter

=head1 SYNOPSIS

In your shell, 

  $ shiroh '俺がメッセージだ'

or

  $ echo '俺こそ真のメッセージだ' | shiroh

=head1 DESCRIPTION

App::Shiroh is a CLI posting tool for twitter

=head1 CONFIG

config-file is ~/.shiroh

This is an example.

  {
     consumar_key        => 'YOUR CONSUMER KEY',
     consumer_secret     => 'YOUR CONSUMER SECRET',
     access_token        => 'YOUR ACCESS TOKEN',
     access_token_secret => 'YOUR ACCESS TOKEN SECRET',
     message_to          => 'some_nickname', ### optional. If defined, send messsage as direct-message to specified account.
  };

=head1 AUTHOR

ytnobody E<lt>ytnobody@gmail.comE<gt>

=head1 SEE ALSO

Net::Twitter::Lite

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
